stages:
  - deploy

before_script:
  - npm ci
deploy:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
  stage: deploy
  image: node:alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.npm
  script:
    - apk add --no-cache bash
    - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - npx expo publish --non-interactive